UPDATE RestaurantData SET restaurant_Name = 'Brown LLC', apartment_building = '22002', street = 'Rodriguez Forks', city = 'Matthewmouth', state = 'VA', zipCode = '15955', contact_No = '1582716061', contact_Email = 'whitecarla@gmail.com', operating_Hours = '22:30 AM - 19:00 PM' WHERE restaurant_id = 'R1';
UPDATE RestaurantData SET restaurant_Name = 'Murphy, Vang and Rivera', apartment_building = '1833', street = 'David Camp', city = 'Richardberg', state = 'AK', zipCode = '74806', contact_No = '1185205449', contact_Email = 'donnahernandez@yahoo.com', operating_Hours = '12:00 AM - 13:00 PM' WHERE restaurant_id = 'R2';
UPDATE RestaurantData SET restaurant_Name = 'Caldwell LLC', apartment_building = '97147', street = 'Mueller Drive', city = 'West Bradley', state = 'KS', zipCode = '63235', contact_No = '0018549773', contact_Email = 'ashleyhansen@nolan-cook.com', operating_Hours = '18:00 AM - 14:30 PM' WHERE restaurant_id = 'R3';
UPDATE RestaurantData SET restaurant_Name = 'Baldwin-Davis', apartment_building = '71896', street = 'Benjamin Shoals', city = 'West Charlesberg', state = 'OK', zipCode = '50057', contact_No = '7419770869', contact_Email = 'daniel28@yahoo.com', operating_Hours = '07:30 AM - 02:00 PM' WHERE restaurant_id = 'R4';
UPDATE RestaurantData SET restaurant_Name = 'Wright, Young and Williams', apartment_building = '7013', street = 'May Ville', city = 'North Karenville', state = 'FL', zipCode = '12206', contact_No = '1981307323', contact_Email = 'smartinez@saunders.com', operating_Hours = '07:00 AM - 10:00 PM' WHERE restaurant_id = 'R5';
UPDATE RestaurantData SET restaurant_Name = 'Gaines Group', apartment_building = '2745', street = 'Marc Corners', city = 'Loriton', state = 'LA', zipCode = '93129', contact_No = '7201467527', contact_Email = 'pattonchristopher@long-buck.net', operating_Hours = '14:30 AM - 00:30 PM' WHERE restaurant_id = 'R6';
UPDATE RestaurantData SET restaurant_Name = 'Haney, Hudson and Davis', apartment_building = '0520', street = 'Brett Roads', city = 'Nguyenburgh', state = 'GA', zipCode = '15408', contact_No = '8157210137', contact_Email = 'brittanywiggins@yahoo.com', operating_Hours = '17:00 AM - 02:30 PM' WHERE restaurant_id = 'R7';
UPDATE RestaurantData SET restaurant_Name = 'Bell-Garrett', apartment_building = '945', street = 'Sanchez Loaf', city = 'Millerchester', state = 'NC', zipCode = '62535', contact_No = '6410134777', contact_Email = 'destiny90@peters.info', operating_Hours = '13:00 AM - 18:00 PM' WHERE restaurant_id = 'R8';
UPDATE RestaurantData SET restaurant_Name = 'Smith and Sons', apartment_building = '63492', street = 'Parker Ford', city = 'Joshuafurt', state = 'GA', zipCode = '02292', contact_No = '1878806739', contact_Email = 'patricia53@willis.org', operating_Hours = '20:00 AM - 19:30 PM' WHERE restaurant_id = 'R9';
UPDATE RestaurantData SET restaurant_Name = 'Schmidt-Nolan', apartment_building = '66744', street = 'Anthony Orchard', city = 'East Jack', state = 'ME', zipCode = '02563', contact_No = '2851777414', contact_Email = 'justinmoon@stevenson.com', operating_Hours = '04:30 AM - 06:30 PM' WHERE restaurant_id = 'R10';
UPDATE RestaurantData SET restaurant_Name = 'Houston-Rodriguez', apartment_building = '2238', street = 'Brandi Hill', city = 'Port Jamie', state = 'VT', zipCode = '80564', contact_No = '0011844315', contact_Email = 'victoria84@guerrero.net', operating_Hours = '04:00 AM - 11:30 PM' WHERE restaurant_id = 'R11';
UPDATE RestaurantData SET restaurant_Name = 'Dunn-Matthews', apartment_building = '74880', street = 'Wilson Shore', city = 'North Lisabury', state = 'ND', zipCode = '20742', contact_No = '1441360581', contact_Email = 'lisawhite@johnson.com', operating_Hours = '01:00 AM - 09:00 PM' WHERE restaurant_id = 'R12';
UPDATE RestaurantData SET restaurant_Name = 'Evans, Miller and Morse', apartment_building = '009', street = 'Stephen Point', city = 'Lake Chadside', state = 'MS', zipCode = '06613', contact_No = '6378953826', contact_Email = 'amandarodriguez@crane.net', operating_Hours = '00:30 AM - 06:30 PM' WHERE restaurant_id = 'R13';
UPDATE RestaurantData SET restaurant_Name = 'Johnson, Thomas and Rodriguez', apartment_building = '382', street = 'Pamela Run', city = 'Wardside', state = 'PA', zipCode = '81908', contact_No = '0019926348', contact_Email = 'austinkatherine@gordon.com', operating_Hours = '12:00 AM - 18:30 PM' WHERE restaurant_id = 'R14';
UPDATE RestaurantData SET restaurant_Name = 'Patton Group', apartment_building = '18414', street = 'Perez Viaduct', city = 'East Jay', state = 'WY', zipCode = '06305', contact_No = '1023146991', contact_Email = 'pnelson@merritt.com', operating_Hours = '10:30 AM - 04:00 PM' WHERE restaurant_id = 'R15';
UPDATE RestaurantData SET restaurant_Name = 'Robertson-Becker', apartment_building = '087', street = 'Christopher Burgs', city = 'Gabrielafort', state = 'AS', zipCode = '13306', contact_No = '6765252195', contact_Email = 'nhaney@oneill.biz', operating_Hours = '23:30 AM - 18:30 PM' WHERE restaurant_id = 'R16';
UPDATE RestaurantData SET restaurant_Name = 'Harrington, Golden and Wood', apartment_building = '3024', street = 'Sharp Bypass', city = 'Vazquezbury', state = 'WA', zipCode = '50453', contact_No = '1683139580', contact_Email = 'christinagonzalez@huynh-ewing.com', operating_Hours = '14:30 AM - 08:30 PM' WHERE restaurant_id = 'R17';
UPDATE RestaurantData SET restaurant_Name = 'Gutierrez Ltd', apartment_building = '3215', street = 'Anita Lake', city = 'Stevenville', state = 'UT', zipCode = '76575', contact_No = '9225635928', contact_Email = 'jmartin@sherman.com', operating_Hours = '13:00 AM - 05:00 PM' WHERE restaurant_id = 'R18';
UPDATE RestaurantData SET restaurant_Name = 'Thompson PLC', apartment_building = '9672', street = 'Williamson River', city = 'New Brittanymouth', state = 'AK', zipCode = '08597', contact_No = '1191184220', contact_Email = 'devinlee@hotmail.com', operating_Hours = '22:00 AM - 21:00 PM' WHERE restaurant_id = 'R19';
UPDATE RestaurantData SET restaurant_Name = 'Mitchell, Todd and Cole', apartment_building = '70437', street = 'Best Cape', city = 'Brownbury', state = 'DC', zipCode = '06831', contact_No = '0014419598', contact_Email = 'jessicafranco@anderson.com', operating_Hours = '09:00 AM - 15:30 PM' WHERE restaurant_id = 'R20';
UPDATE RestaurantData SET restaurant_Name = 'Riddle-Johnson', apartment_building = '79985', street = 'Edward Crossroad', city = 'Lake Holly', state = 'LA', zipCode = '65202', contact_No = '1864857682', contact_Email = 'joseph54@gmail.com', operating_Hours = '10:00 AM - 11:00 PM' WHERE restaurant_id = 'R21';
UPDATE RestaurantData SET restaurant_Name = 'Roberts, Lara and Nguyen', apartment_building = '13901', street = 'Brown Mills', city = 'Davidhaven', state = 'AR', zipCode = '34325', contact_No = '2438139569', contact_Email = 'donald96@taylor.biz', operating_Hours = '00:30 AM - 10:00 PM' WHERE restaurant_id = 'R22';
UPDATE RestaurantData SET restaurant_Name = 'Hendrix, Mcdowell and Garcia', apartment_building = '819', street = 'Alisha Court', city = 'Kellyshire', state = 'AZ', zipCode = '93447', contact_No = '1145488916', contact_Email = 'ginaherrera@gmail.com', operating_Hours = '10:00 AM - 12:30 PM' WHERE restaurant_id = 'R23';
UPDATE RestaurantData SET restaurant_Name = 'Krause LLC', apartment_building = '302', street = 'David Street', city = 'Youngfort', state = 'NY', zipCode = '53012', contact_No = '1587899952', contact_Email = 'bkim@gmail.com', operating_Hours = '10:30 AM - 20:30 PM' WHERE restaurant_id = 'R24';
UPDATE RestaurantData SET restaurant_Name = 'Bush, Casey and Hardin', apartment_building = '044', street = 'Campbell Harbors', city = 'North Angelaview', state = 'NY', zipCode = '59972', contact_No = '5506052903', contact_Email = 'singhmario@yahoo.com', operating_Hours = '16:00 AM - 17:30 PM' WHERE restaurant_id = 'R25';
UPDATE RestaurantData SET restaurant_Name = 'Stewart, Weber and Logan', apartment_building = '97555', street = 'King Meadows', city = 'Lake Thomasville', state = 'RI', zipCode = '90732', contact_No = '6048350878', contact_Email = 'tim01@yahoo.com', operating_Hours = '01:30 AM - 12:00 PM' WHERE restaurant_id = 'R26';
UPDATE RestaurantData SET restaurant_Name = 'Martin, Fitzgerald and Carlson', apartment_building = '5735', street = 'Nicole Run', city = 'Jimenezfurt', state = 'WA', zipCode = '86184', contact_No = '5924800015', contact_Email = 'hjenkins@hotmail.com', operating_Hours = '13:30 AM - 06:30 PM' WHERE restaurant_id = 'R27';
UPDATE RestaurantData SET restaurant_Name = 'Johnson LLC', apartment_building = '298', street = 'Hill Throughway', city = 'Humphreyland', state = 'FM', zipCode = '67011', contact_No = '1056193454', contact_Email = 'julie92@ware-blankenship.net', operating_Hours = '20:30 AM - 04:30 PM' WHERE restaurant_id = 'R28';
UPDATE RestaurantData SET restaurant_Name = 'Hall PLC', apartment_building = '25168', street = 'Brittney Stream', city = 'Kingville', state = 'VI', zipCode = '64484', contact_No = '9420114772', contact_Email = 'williamball@dennis-smith.net', operating_Hours = '08:30 AM - 07:30 PM' WHERE restaurant_id = 'R29';
UPDATE RestaurantData SET restaurant_Name = 'Fuller, Klein and Ortiz', apartment_building = '45499', street = 'Christopher Park', city = 'West David', state = 'ND', zipCode = '59924', contact_No = '2470376844', contact_Email = 'gingram@ward.com', operating_Hours = '09:00 AM - 14:30 PM' WHERE restaurant_id = 'R30';
UPDATE RestaurantData SET restaurant_Name = 'Owens, Green and Fletcher', apartment_building = '652', street = 'Erika Unions', city = 'Douglasland', state = 'NE', zipCode = '59625', contact_No = '4353068254', contact_Email = 'jessicaholt@gmail.com', operating_Hours = '09:00 AM - 14:00 PM' WHERE restaurant_id = 'R31';
UPDATE RestaurantData SET restaurant_Name = 'Jackson-Ho', apartment_building = '524', street = 'Crane Via', city = 'Port Nicole', state = 'AL', zipCode = '09246', contact_No = '0012484233', contact_Email = 'morganwilliams@gmail.com', operating_Hours = '07:00 AM - 08:00 PM' WHERE restaurant_id = 'R32';
UPDATE RestaurantData SET restaurant_Name = 'Peterson, Kent and Rivera', apartment_building = '08458', street = 'Sexton Drives', city = 'Tammychester', state = 'PW', zipCode = '36301', contact_No = '8302936719', contact_Email = 'dillondanielle@lynch-richardson.org', operating_Hours = '16:00 AM - 00:00 PM' WHERE restaurant_id = 'R33';
UPDATE RestaurantData SET restaurant_Name = 'Hale, Howell and Clark', apartment_building = '6375', street = 'Michael Crossing', city = 'New Tammy', state = 'DC', zipCode = '83459', contact_No = '6294787967', contact_Email = 'cwest@hughes-blankenship.info', operating_Hours = '06:30 AM - 04:30 PM' WHERE restaurant_id = 'R34';
UPDATE RestaurantData SET restaurant_Name = 'Barr-Miller', apartment_building = '695', street = 'Good Forges', city = 'Pittmanbury', state = 'MT', zipCode = '99068', contact_No = '3563634719', contact_Email = 'holdenvictor@payne.info', operating_Hours = '17:00 AM - 15:00 PM' WHERE restaurant_id = 'R35';
UPDATE RestaurantData SET restaurant_Name = 'Young-Powell', apartment_building = '0046', street = 'Brian Run', city = 'Johnsonberg', state = 'WI', zipCode = '28400', contact_No = '1951970223', contact_Email = 'ubennett@castaneda.com', operating_Hours = '18:30 AM - 16:00 PM' WHERE restaurant_id = 'R36';
UPDATE RestaurantData SET restaurant_Name = 'Robinson-Lee', apartment_building = '083', street = 'Mcgee Keys', city = 'South Andreton', state = 'IL', zipCode = '32595', contact_No = '4906835961', contact_Email = 'dannybrooks@nelson-salazar.com', operating_Hours = '20:30 AM - 15:30 PM' WHERE restaurant_id = 'R37';
UPDATE RestaurantData SET restaurant_Name = 'Lawrence-Moore', apartment_building = '703', street = 'Andrade Lodge', city = 'West Joseph', state = 'WV', zipCode = '63804', contact_No = '0013684824', contact_Email = 'westjasmine@pratt.com', operating_Hours = '05:00 AM - 02:00 PM' WHERE restaurant_id = 'R38';
UPDATE RestaurantData SET restaurant_Name = 'Stone and Sons', apartment_building = '888', street = 'Heather Meadows', city = 'Joshuatown', state = 'PA', zipCode = '64638', contact_No = '6479989352', contact_Email = 'bestdennis@yahoo.com', operating_Hours = '09:30 AM - 18:30 PM' WHERE restaurant_id = 'R39';
UPDATE RestaurantData SET restaurant_Name = 'Klein, Alvarez and Johnson', apartment_building = '4990', street = 'Taylor Burgs', city = 'Boyerland', state = 'TX', zipCode = '78296', contact_No = '1138954069', contact_Email = 'caseyjackson@clark-carey.org', operating_Hours = '21:30 AM - 06:00 PM' WHERE restaurant_id = 'R40';
UPDATE RestaurantData SET restaurant_Name = 'Miller, Williams and Brown', apartment_building = '43617', street = 'Tom Centers', city = 'Port Garymouth', state = 'CA', zipCode = '74828', contact_No = '7234638744', contact_Email = 'lori13@barajas.info', operating_Hours = '02:00 AM - 17:00 PM' WHERE restaurant_id = 'R41';
UPDATE RestaurantData SET restaurant_Name = 'Johnson-Rivas', apartment_building = '2859', street = 'Mclean Squares', city = 'Huffport', state = 'CT', zipCode = '59099', contact_No = '0016590482', contact_Email = 'rebecca70@yahoo.com', operating_Hours = '15:30 AM - 21:30 PM' WHERE restaurant_id = 'R42';
UPDATE RestaurantData SET restaurant_Name = 'Moore, Rivera and Hall', apartment_building = '17509', street = 'Duncan Gardens', city = 'Port Jennifer', state = 'LA', zipCode = '70158', contact_No = '9131732543', contact_Email = 'christianlove@williams-ford.info', operating_Hours = '06:30 AM - 09:30 PM' WHERE restaurant_id = 'R43';
UPDATE RestaurantData SET restaurant_Name = 'Martin Group', apartment_building = '918', street = 'Kimberly Mountain', city = 'West Krystalstad', state = 'PW', zipCode = '57960', contact_No = '1213919016', contact_Email = 'abigailmcgee@yahoo.com', operating_Hours = '08:00 AM - 11:00 PM' WHERE restaurant_id = 'R44';
UPDATE RestaurantData SET restaurant_Name = 'Lewis PLC', apartment_building = '12921', street = 'Michael Extension', city = 'Dustintown', state = 'NC', zipCode = '56963', contact_No = '0014047343', contact_Email = 'john75@king.com', operating_Hours = '19:30 AM - 13:00 PM' WHERE restaurant_id = 'R45';
UPDATE RestaurantData SET restaurant_Name = 'Chan LLC', apartment_building = '037', street = 'David Cliff', city = 'North Shawnborough', state = 'NE', zipCode = '83308', contact_No = '8938067919', contact_Email = 'sabrina78@young-green.com', operating_Hours = '17:30 AM - 16:00 PM' WHERE restaurant_id = 'R46';
UPDATE RestaurantData SET restaurant_Name = 'Mendoza-Perez', apartment_building = '51063', street = 'Lawrence Roads', city = 'Nguyenmouth', state = 'ND', zipCode = '24553', contact_No = '5538094804', contact_Email = 'jerry45@gmail.com', operating_Hours = '20:00 AM - 16:30 PM' WHERE restaurant_id = 'R47';
UPDATE RestaurantData SET restaurant_Name = 'Armstrong-Wood', apartment_building = '94461', street = 'Reyes Knolls', city = 'South Patriciatown', state = 'ID', zipCode = '86550', contact_No = '5601062528', contact_Email = 'elizabethford@gmail.com', operating_Hours = '11:00 AM - 20:00 PM' WHERE restaurant_id = 'R48';
UPDATE RestaurantData SET restaurant_Name = 'Spencer-Jacobs', apartment_building = '79896', street = 'Angela Key', city = 'Riverahaven', state = 'NY', zipCode = '25555', contact_No = '0010373636', contact_Email = 'markbarnett@campbell.com', operating_Hours = '11:00 AM - 21:30 PM' WHERE restaurant_id = 'R49';
UPDATE RestaurantData SET restaurant_Name = 'Schneider and Sons', apartment_building = '50633', street = 'Bradley Shores', city = 'Santiagoburgh', state = 'TX', zipCode = '96232', contact_No = '4961429823', contact_Email = 'maryjones@robertson.com', operating_Hours = '16:30 AM - 10:00 PM' WHERE restaurant_id = 'R50';
DELETE FROM RestaurantFacility WHERE restaurant_id = 'R1';
DELETE FROM RestaurantFacility WHERE restaurant_id = 'R2';
DELETE FROM RestaurantFacility WHERE restaurant_id = 'R3';
DELETE FROM RestaurantFacility WHERE restaurant_id = 'R4';
DELETE FROM RestaurantFacility WHERE restaurant_id = 'R5';
DELETE FROM RestaurantFacility WHERE restaurant_id = 'R6';
DELETE FROM RestaurantFacility WHERE restaurant_id = 'R7';
DELETE FROM RestaurantFacility WHERE restaurant_id = 'R8';
DELETE FROM RestaurantFacility WHERE restaurant_id = 'R9';
DELETE FROM RestaurantFacility WHERE restaurant_id = 'R10';
DELETE FROM RestaurantFacility WHERE restaurant_id = 'R11';
DELETE FROM RestaurantFacility WHERE restaurant_id = 'R12';
DELETE FROM RestaurantFacility WHERE restaurant_id = 'R13';
DELETE FROM RestaurantFacility WHERE restaurant_id = 'R14';
DELETE FROM RestaurantFacility WHERE restaurant_id = 'R15';
INSERT INTO RestaurantFacility (restaurant_id, facility) VALUES ('R1', 'Dine-in');
INSERT INTO RestaurantFacility (restaurant_id, facility) VALUES ('R1', 'Delivery');
INSERT INTO RestaurantFacility (restaurant_id, facility) VALUES ('R2', 'Dine-in');
INSERT INTO RestaurantFacility (restaurant_id, facility) VALUES ('R2', 'Delivery');
INSERT INTO RestaurantFacility (restaurant_id, facility) VALUES ('R2', 'Drive-thru');
INSERT INTO RestaurantFacility (restaurant_id, facility) VALUES ('R2', 'Pick up');
INSERT INTO RestaurantFacility (restaurant_id, facility) VALUES ('R3', 'Pick up');
INSERT INTO RestaurantFacility (restaurant_id, facility) VALUES ('R3', 'Dine-in');
INSERT INTO RestaurantFacility (restaurant_id, facility) VALUES ('R4', 'Delivery');
INSERT INTO RestaurantFacility (restaurant_id, facility) VALUES ('R5', 'Pick up');
INSERT INTO RestaurantFacility (restaurant_id, facility) VALUES ('R6', 'Delivery');
INSERT INTO RestaurantFacility (restaurant_id, facility) VALUES ('R6', 'Dine-in');
INSERT INTO RestaurantFacility (restaurant_id, facility) VALUES ('R6', 'Drive-thru');
INSERT INTO RestaurantFacility (restaurant_id, facility) VALUES ('R6', 'Pick up');
INSERT INTO RestaurantFacility (restaurant_id, facility) VALUES ('R7', 'Drive-thru');
INSERT INTO RestaurantFacility (restaurant_id, facility) VALUES ('R8', 'Drive-thru');
INSERT INTO RestaurantFacility (restaurant_id, facility) VALUES ('R8', 'Dine-in');
INSERT INTO RestaurantFacility (restaurant_id, facility) VALUES ('R8', 'Pick up');
INSERT INTO RestaurantFacility (restaurant_id, facility) VALUES ('R9', 'Dine-in');
INSERT INTO RestaurantFacility (restaurant_id, facility) VALUES ('R9', 'Delivery');
INSERT INTO RestaurantFacility (restaurant_id, facility) VALUES ('R9', 'Pick up');
INSERT INTO RestaurantFacility (restaurant_id, facility) VALUES ('R9', 'Drive-thru');
INSERT INTO RestaurantFacility (restaurant_id, facility) VALUES ('R10', 'Dine-in');
INSERT INTO RestaurantFacility (restaurant_id, facility) VALUES ('R10', 'Delivery');
INSERT INTO RestaurantFacility (restaurant_id, facility) VALUES ('R10', 'Drive-thru');
INSERT INTO RestaurantFacility (restaurant_id, facility) VALUES ('R11', 'Pick up');
INSERT INTO RestaurantFacility (restaurant_id, facility) VALUES ('R12', 'Delivery');
INSERT INTO RestaurantFacility (restaurant_id, facility) VALUES ('R13', 'Pick up');
INSERT INTO RestaurantFacility (restaurant_id, facility) VALUES ('R13', 'Drive-thru');
INSERT INTO RestaurantFacility (restaurant_id, facility) VALUES ('R13', 'Delivery');
INSERT INTO RestaurantFacility (restaurant_id, facility) VALUES ('R13', 'Dine-in');
INSERT INTO RestaurantFacility (restaurant_id, facility) VALUES ('R14', 'Drive-thru');
INSERT INTO RestaurantFacility (restaurant_id, facility) VALUES ('R15', 'Drive-thru');
INSERT INTO RestaurantFacility (restaurant_id, facility) VALUES ('R15', 'Pick up');
INSERT INTO RestaurantFacility (restaurant_id, facility) VALUES ('R15', 'Dine-in');
UPDATE ItemData SET item_name = 'Spaghetti Carbonara', cuisine_type = 'Italian', price = '26.39', calories = '732', item_type = 'Starter', preparation_time = '115' WHERE item_id = 'I1';
UPDATE ItemData SET item_name = 'Burrito', cuisine_type = 'Mexican', price = '27.02', calories = '955', item_type = 'Dessert', preparation_time = '61' WHERE item_id = 'I2';
UPDATE ItemData SET item_name = 'Butter Chicken', cuisine_type = 'Indian', price = '42.76', calories = '448', item_type = 'Main Course', preparation_time = '87' WHERE item_id = 'I3';
UPDATE ItemData SET item_name = 'Tempura', cuisine_type = 'Japanese', price = '14.21', calories = '945', item_type = 'Dessert', preparation_time = '47' WHERE item_id = 'I4';
UPDATE ItemData SET item_name = 'Sweet and Sour Pork', cuisine_type = 'Chinese', price = '32.42', calories = '254', item_type = 'Starter', preparation_time = '70' WHERE item_id = 'I5';
UPDATE ItemData SET item_name = 'Mapo Tofu', cuisine_type = 'Chinese', price = '22.49', calories = '365', item_type = 'Dessert', preparation_time = '77' WHERE item_id = 'I6';
UPDATE ItemData SET item_name = 'Lasagna', cuisine_type = 'Italian', price = '32.19', calories = '260', item_type = 'Starter', preparation_time = '65' WHERE item_id = 'I7';
UPDATE ItemData SET item_name = 'Spaghetti Carbonara', cuisine_type = 'Italian', price = '18.45', calories = '551', item_type = 'Dessert', preparation_time = '7' WHERE item_id = 'I8';
UPDATE ItemData SET item_name = 'Chiles Rellenos', cuisine_type = 'Mexican', price = '14.26', calories = '721', item_type = 'Starter', preparation_time = '55' WHERE item_id = 'I9';
UPDATE ItemData SET item_name = 'Churros', cuisine_type = 'Mexican', price = '36.56', calories = '145', item_type = 'Starter', preparation_time = '23' WHERE item_id = 'I10';
UPDATE ItemData SET item_name = 'Chiles Rellenos', cuisine_type = 'Mexican', price = '29.02', calories = '761', item_type = 'Beverage', preparation_time = '96' WHERE item_id = 'I11';
UPDATE ItemData SET item_name = 'Mapo Tofu', cuisine_type = 'Chinese', price = '40.78', calories = '337', item_type = 'Beverage', preparation_time = '106' WHERE item_id = 'I12';
UPDATE ItemData SET item_name = 'Tacos', cuisine_type = 'Mexican', price = '6.85', calories = '885', item_type = 'Starter', preparation_time = '70' WHERE item_id = 'I13';
UPDATE ItemData SET item_name = 'Tacos', cuisine_type = 'Mexican', price = '7.07', calories = '960', item_type = 'Starter', preparation_time = '79' WHERE item_id = 'I14';
UPDATE ItemData SET item_name = 'Miso Soup', cuisine_type = 'Japanese', price = '26.02', calories = '956', item_type = 'Beverage', preparation_time = '103' WHERE item_id = 'I15';
UPDATE ItemData SET item_name = 'Churros', cuisine_type = 'Mexican', price = '37.35', calories = '238', item_type = 'Dessert', preparation_time = '76' WHERE item_id = 'I16';
UPDATE ItemData SET item_name = 'Enchiladas', cuisine_type = 'Mexican', price = '48.45', calories = '142', item_type = 'Starter', preparation_time = '79' WHERE item_id = 'I17';
UPDATE ItemData SET item_name = 'Tacos', cuisine_type = 'Mexican', price = '17.28', calories = '361', item_type = 'Main Course', preparation_time = '106' WHERE item_id = 'I18';
UPDATE ItemData SET item_name = 'Tiramisu', cuisine_type = 'Italian', price = '13.68', calories = '578', item_type = 'Starter', preparation_time = '60' WHERE item_id = 'I19';
UPDATE ItemData SET item_name = 'Sushi', cuisine_type = 'Japanese', price = '30.64', calories = '339', item_type = 'Starter', preparation_time = '13' WHERE item_id = 'I20';
UPDATE ItemData SET item_name = 'Wonton Soup', cuisine_type = 'Chinese', price = '23.47', calories = '827', item_type = 'Starter', preparation_time = '18' WHERE item_id = 'I21';
UPDATE ItemData SET item_name = 'Biryani', cuisine_type = 'Indian', price = '20.99', calories = '532', item_type = 'Beverage', preparation_time = '33' WHERE item_id = 'I22';
UPDATE ItemData SET item_name = 'Wonton Soup', cuisine_type = 'Chinese', price = '24.66', calories = '212', item_type = 'Dessert', preparation_time = '60' WHERE item_id = 'I23';
UPDATE ItemData SET item_name = 'Mapo Tofu', cuisine_type = 'Chinese', price = '40.88', calories = '734', item_type = 'Starter', preparation_time = '53' WHERE item_id = 'I24';
UPDATE ItemData SET item_name = 'Enchiladas', cuisine_type = 'Mexican', price = '13.98', calories = '953', item_type = 'Dessert', preparation_time = '66' WHERE item_id = 'I25';
UPDATE ItemData SET item_name = 'Sweet and Sour Pork', cuisine_type = 'Chinese', price = '16.72', calories = '267', item_type = 'Main Course', preparation_time = '88' WHERE item_id = 'I26';
UPDATE ItemData SET item_name = 'Mapo Tofu', cuisine_type = 'Chinese', price = '40.9', calories = '445', item_type = 'Beverage', preparation_time = '28' WHERE item_id = 'I27';
UPDATE ItemData SET item_name = 'Tempura', cuisine_type = 'Japanese', price = '41.4', calories = '298', item_type = 'Starter', preparation_time = '17' WHERE item_id = 'I28';
UPDATE ItemData SET item_name = 'Chiles Rellenos', cuisine_type = 'Mexican', price = '38.48', calories = '177', item_type = 'Beverage', preparation_time = '70' WHERE item_id = 'I29';
UPDATE ItemData SET item_name = 'Tempura', cuisine_type = 'Japanese', price = '39.67', calories = '319', item_type = 'Starter', preparation_time = '54' WHERE item_id = 'I30';
UPDATE ItemData SET item_name = 'Tiramisu', cuisine_type = 'Italian', price = '43.71', calories = '332', item_type = 'Dessert', preparation_time = '117' WHERE item_id = 'I31';
UPDATE ItemData SET item_name = 'Enchiladas', cuisine_type = 'Mexican', price = '5.19', calories = '840', item_type = 'Starter', preparation_time = '31' WHERE item_id = 'I32';
UPDATE ItemData SET item_name = 'Chole Bhature', cuisine_type = 'Indian', price = '18.14', calories = '391', item_type = 'Dessert', preparation_time = '106' WHERE item_id = 'I33';
UPDATE ItemData SET item_name = 'Ramen', cuisine_type = 'Japanese', price = '25.63', calories = '111', item_type = 'Dessert', preparation_time = '30' WHERE item_id = 'I34';
UPDATE ItemData SET item_name = 'Tacos', cuisine_type = 'Mexican', price = '42.81', calories = '990', item_type = 'Main Course', preparation_time = '105' WHERE item_id = 'I35';
UPDATE ItemData SET item_name = 'Chole Bhature', cuisine_type = 'Indian', price = '36.83', calories = '373', item_type = 'Starter', preparation_time = '45' WHERE item_id = 'I36';
UPDATE ItemData SET item_name = 'Tacos', cuisine_type = 'Mexican', price = '26.91', calories = '951', item_type = 'Beverage', preparation_time = '88' WHERE item_id = 'I37';
UPDATE ItemData SET item_name = 'Ramen', cuisine_type = 'Japanese', price = '13.48', calories = '949', item_type = 'Beverage', preparation_time = '93' WHERE item_id = 'I38';
UPDATE ItemData SET item_name = 'Tacos', cuisine_type = 'Mexican', price = '19.93', calories = '260', item_type = 'Starter', preparation_time = '70' WHERE item_id = 'I39';
UPDATE ItemData SET item_name = 'Tacos', cuisine_type = 'Mexican', price = '36.59', calories = '253', item_type = 'Dessert', preparation_time = '60' WHERE item_id = 'I40';
UPDATE ItemData SET item_name = 'Tempura', cuisine_type = 'Japanese', price = '10.73', calories = '934', item_type = 'Beverage', preparation_time = '13' WHERE item_id = 'I41';
UPDATE ItemData SET item_name = 'Tiramisu', cuisine_type = 'Italian', price = '33.03', calories = '800', item_type = 'Main Course', preparation_time = '99' WHERE item_id = 'I42';
UPDATE ItemData SET item_name = 'Risotto', cuisine_type = 'Italian', price = '16.29', calories = '278', item_type = 'Dessert', preparation_time = '94' WHERE item_id = 'I43';
UPDATE ItemData SET item_name = 'Spaghetti Carbonara', cuisine_type = 'Italian', price = '25.46', calories = '992', item_type = 'Dessert', preparation_time = '20' WHERE item_id = 'I44';
UPDATE ItemData SET item_name = 'Udon', cuisine_type = 'Japanese', price = '37.49', calories = '260', item_type = 'Starter', preparation_time = '111' WHERE item_id = 'I45';
UPDATE ItemData SET item_name = 'Fried Rice', cuisine_type = 'Chinese', price = '22.64', calories = '483', item_type = 'Main Course', preparation_time = '113' WHERE item_id = 'I46';
UPDATE ItemData SET item_name = 'Sweet and Sour Pork', cuisine_type = 'Chinese', price = '26.84', calories = '799', item_type = 'Beverage', preparation_time = '115' WHERE item_id = 'I47';
UPDATE ItemData SET item_name = 'Tacos', cuisine_type = 'Mexican', price = '42.17', calories = '712', item_type = 'Dessert', preparation_time = '56' WHERE item_id = 'I48';
UPDATE ItemData SET item_name = 'Chole Bhature', cuisine_type = 'Indian', price = '49.1', calories = '974', item_type = 'Dessert', preparation_time = '52' WHERE item_id = 'I49';
UPDATE ItemData SET item_name = 'Butter Chicken', cuisine_type = 'Indian', price = '15.61', calories = '169', item_type = 'Main Course', preparation_time = '86' WHERE item_id = 'I50';
UPDATE ItemData SET item_name = 'Chole Bhature', cuisine_type = 'Indian', price = '26.16', calories = '284', item_type = 'Beverage', preparation_time = '34' WHERE item_id = 'I51';
UPDATE ItemData SET item_name = 'Tempura', cuisine_type = 'Japanese', price = '25.93', calories = '121', item_type = 'Beverage', preparation_time = '26' WHERE item_id = 'I52';
UPDATE ItemData SET item_name = 'Wonton Soup', cuisine_type = 'Chinese', price = '35.64', calories = '867', item_type = 'Dessert', preparation_time = '52' WHERE item_id = 'I53';
UPDATE ItemData SET item_name = 'Rogan Josh', cuisine_type = 'Indian', price = '32.26', calories = '785', item_type = 'Beverage', preparation_time = '89' WHERE item_id = 'I54';
UPDATE ItemData SET item_name = 'Wonton Soup', cuisine_type = 'Chinese', price = '46.77', calories = '751', item_type = 'Dessert', preparation_time = '33' WHERE item_id = 'I55';
UPDATE ItemData SET item_name = 'Risotto', cuisine_type = 'Italian', price = '18.31', calories = '125', item_type = 'Starter', preparation_time = '102' WHERE item_id = 'I56';
UPDATE ItemData SET item_name = 'Pizza Margherita', cuisine_type = 'Italian', price = '31.33', calories = '968', item_type = 'Beverage', preparation_time = '92' WHERE item_id = 'I57';
UPDATE ItemData SET item_name = 'Lasagna', cuisine_type = 'Italian', price = '31.67', calories = '254', item_type = 'Main Course', preparation_time = '93' WHERE item_id = 'I58';
UPDATE ItemData SET item_name = 'Miso Soup', cuisine_type = 'Japanese', price = '15.94', calories = '915', item_type = 'Main Course', preparation_time = '23' WHERE item_id = 'I59';
UPDATE ItemData SET item_name = 'Mapo Tofu', cuisine_type = 'Chinese', price = '46.01', calories = '349', item_type = 'Main Course', preparation_time = '34' WHERE item_id = 'I60';
UPDATE ItemData SET item_name = 'Sushi', cuisine_type = 'Japanese', price = '21.5', calories = '946', item_type = 'Starter', preparation_time = '64' WHERE item_id = 'I61';
UPDATE ItemData SET item_name = 'Kung Pao Chicken', cuisine_type = 'Chinese', price = '10.78', calories = '258', item_type = 'Beverage', preparation_time = '33' WHERE item_id = 'I62';
UPDATE ItemData SET item_name = 'Pizza Margherita', cuisine_type = 'Italian', price = '33.09', calories = '628', item_type = 'Dessert', preparation_time = '24' WHERE item_id = 'I63';
UPDATE ItemData SET item_name = 'Chole Bhature', cuisine_type = 'Indian', price = '44.75', calories = '659', item_type = 'Beverage', preparation_time = '42' WHERE item_id = 'I64';
UPDATE ItemData SET item_name = 'Risotto', cuisine_type = 'Italian', price = '39.18', calories = '150', item_type = 'Starter', preparation_time = '34' WHERE item_id = 'I65';
UPDATE ItemData SET item_name = 'Wonton Soup', cuisine_type = 'Chinese', price = '17.43', calories = '149', item_type = 'Beverage', preparation_time = '73' WHERE item_id = 'I66';
UPDATE ItemData SET item_name = 'Enchiladas', cuisine_type = 'Mexican', price = '6.06', calories = '796', item_type = 'Starter', preparation_time = '81' WHERE item_id = 'I67';
UPDATE ItemData SET item_name = 'Miso Soup', cuisine_type = 'Japanese', price = '27.99', calories = '920', item_type = 'Main Course', preparation_time = '116' WHERE item_id = 'I68';
UPDATE ItemData SET item_name = 'Chole Bhature', cuisine_type = 'Indian', price = '20.18', calories = '848', item_type = 'Beverage', preparation_time = '48' WHERE item_id = 'I69';
UPDATE ItemData SET item_name = 'Sushi', cuisine_type = 'Japanese', price = '28.64', calories = '775', item_type = 'Main Course', preparation_time = '88' WHERE item_id = 'I70';
UPDATE ItemData SET item_name = 'Chiles Rellenos', cuisine_type = 'Mexican', price = '12.16', calories = '728', item_type = 'Starter', preparation_time = '105' WHERE item_id = 'I71';
UPDATE ItemData SET item_name = 'Tacos', cuisine_type = 'Mexican', price = '16.18', calories = '817', item_type = 'Beverage', preparation_time = '93' WHERE item_id = 'I72';
UPDATE ItemData SET item_name = 'Udon', cuisine_type = 'Japanese', price = '49.76', calories = '606', item_type = 'Beverage', preparation_time = '75' WHERE item_id = 'I73';
UPDATE ItemData SET item_name = 'Fried Rice', cuisine_type = 'Chinese', price = '17.78', calories = '865', item_type = 'Beverage', preparation_time = '107' WHERE item_id = 'I74';
UPDATE ItemData SET item_name = 'Ramen', cuisine_type = 'Japanese', price = '38.7', calories = '990', item_type = 'Main Course', preparation_time = '25' WHERE item_id = 'I75';
UPDATE ItemData SET item_name = 'Kung Pao Chicken', cuisine_type = 'Chinese', price = '37.62', calories = '323', item_type = 'Main Course', preparation_time = '119' WHERE item_id = 'I76';
UPDATE ItemData SET item_name = 'Udon', cuisine_type = 'Japanese', price = '27.07', calories = '999', item_type = 'Main Course', preparation_time = '120' WHERE item_id = 'I77';
UPDATE ItemData SET item_name = 'Risotto', cuisine_type = 'Italian', price = '5.42', calories = '157', item_type = 'Beverage', preparation_time = '8' WHERE item_id = 'I78';
UPDATE ItemData SET item_name = 'Mapo Tofu', cuisine_type = 'Chinese', price = '15.18', calories = '895', item_type = 'Starter', preparation_time = '55' WHERE item_id = 'I79';
UPDATE ItemData SET item_name = 'Sweet and Sour Pork', cuisine_type = 'Chinese', price = '46.77', calories = '194', item_type = 'Beverage', preparation_time = '43' WHERE item_id = 'I80';
UPDATE ItemData SET item_name = 'Fried Rice', cuisine_type = 'Chinese', price = '34.01', calories = '439', item_type = 'Dessert', preparation_time = '41' WHERE item_id = 'I81';
UPDATE ItemData SET item_name = 'Spaghetti Carbonara', cuisine_type = 'Italian', price = '31.01', calories = '775', item_type = 'Beverage', preparation_time = '25' WHERE item_id = 'I82';
UPDATE ItemData SET item_name = 'Miso Soup', cuisine_type = 'Japanese', price = '36.68', calories = '321', item_type = 'Beverage', preparation_time = '105' WHERE item_id = 'I83';
UPDATE ItemData SET item_name = 'Pizza Margherita', cuisine_type = 'Italian', price = '39.05', calories = '177', item_type = 'Dessert', preparation_time = '100' WHERE item_id = 'I84';
UPDATE ItemData SET item_name = 'Ramen', cuisine_type = 'Japanese', price = '37.59', calories = '389', item_type = 'Dessert', preparation_time = '61' WHERE item_id = 'I85';
UPDATE ItemData SET item_name = 'Ramen', cuisine_type = 'Japanese', price = '38.07', calories = '765', item_type = 'Beverage', preparation_time = '33' WHERE item_id = 'I86';
UPDATE ItemData SET item_name = 'Lasagna', cuisine_type = 'Italian', price = '34.2', calories = '895', item_type = 'Main Course', preparation_time = '69' WHERE item_id = 'I87';
UPDATE ItemData SET item_name = 'Mapo Tofu', cuisine_type = 'Chinese', price = '48.65', calories = '146', item_type = 'Main Course', preparation_time = '60' WHERE item_id = 'I88';
UPDATE ItemData SET item_name = 'Spaghetti Carbonara', cuisine_type = 'Italian', price = '42.93', calories = '634', item_type = 'Starter', preparation_time = '92' WHERE item_id = 'I89';
UPDATE ItemData SET item_name = 'Tacos', cuisine_type = 'Mexican', price = '49.99', calories = '945', item_type = 'Starter', preparation_time = '99' WHERE item_id = 'I90';
UPDATE ItemData SET item_name = 'Sushi', cuisine_type = 'Japanese', price = '7.29', calories = '283', item_type = 'Dessert', preparation_time = '113' WHERE item_id = 'I91';
UPDATE ItemData SET item_name = 'Sushi', cuisine_type = 'Japanese', price = '10.56', calories = '495', item_type = 'Starter', preparation_time = '25' WHERE item_id = 'I92';
UPDATE ItemData SET item_name = 'Butter Chicken', cuisine_type = 'Indian', price = '47.38', calories = '104', item_type = 'Beverage', preparation_time = '60' WHERE item_id = 'I93';
UPDATE ItemData SET item_name = 'Udon', cuisine_type = 'Japanese', price = '32.36', calories = '288', item_type = 'Main Course', preparation_time = '41' WHERE item_id = 'I94';
UPDATE ItemData SET item_name = 'Wonton Soup', cuisine_type = 'Chinese', price = '21.51', calories = '845', item_type = 'Main Course', preparation_time = '88' WHERE item_id = 'I95';
UPDATE ItemData SET item_name = 'Rogan Josh', cuisine_type = 'Indian', price = '6.88', calories = '298', item_type = 'Beverage', preparation_time = '103' WHERE item_id = 'I96';
UPDATE ItemData SET item_name = 'Lasagna', cuisine_type = 'Italian', price = '29.71', calories = '555', item_type = 'Beverage', preparation_time = '34' WHERE item_id = 'I97';
UPDATE ItemData SET item_name = 'Biryani', cuisine_type = 'Indian', price = '44.27', calories = '129', item_type = 'Dessert', preparation_time = '93' WHERE item_id = 'I98';
UPDATE ItemData SET item_name = 'Spaghetti Carbonara', cuisine_type = 'Italian', price = '31.45', calories = '430', item_type = 'Main Course', preparation_time = '34' WHERE item_id = 'I99';
UPDATE ItemData SET item_name = 'Rogan Josh', cuisine_type = 'Indian', price = '39.06', calories = '126', item_type = 'Starter', preparation_time = '101' WHERE item_id = 'I100';
UPDATE ItemData SET item_name = 'Enchiladas', cuisine_type = 'Mexican', price = '49.7', calories = '925', item_type = 'Beverage', preparation_time = '87' WHERE item_id = 'I101';
UPDATE ItemData SET item_name = 'Udon', cuisine_type = 'Japanese', price = '5.09', calories = '771', item_type = 'Beverage', preparation_time = '42' WHERE item_id = 'I102';
UPDATE ItemData SET item_name = 'Risotto', cuisine_type = 'Italian', price = '49.62', calories = '795', item_type = 'Beverage', preparation_time = '8' WHERE item_id = 'I103';
UPDATE ItemData SET item_name = 'Tiramisu', cuisine_type = 'Italian', price = '29.0', calories = '272', item_type = 'Starter', preparation_time = '41' WHERE item_id = 'I104';
UPDATE ItemData SET item_name = 'Chole Bhature', cuisine_type = 'Indian', price = '41.14', calories = '204', item_type = 'Beverage', preparation_time = '111' WHERE item_id = 'I105';
UPDATE ItemData SET item_name = 'Udon', cuisine_type = 'Japanese', price = '42.39', calories = '380', item_type = 'Beverage', preparation_time = '68' WHERE item_id = 'I106';
UPDATE ItemData SET item_name = 'Lasagna', cuisine_type = 'Italian', price = '32.11', calories = '286', item_type = 'Main Course', preparation_time = '79' WHERE item_id = 'I107';
UPDATE ItemData SET item_name = 'Miso Soup', cuisine_type = 'Japanese', price = '18.55', calories = '380', item_type = 'Main Course', preparation_time = '58' WHERE item_id = 'I108';
UPDATE ItemData SET item_name = 'Wonton Soup', cuisine_type = 'Chinese', price = '31.95', calories = '686', item_type = 'Starter', preparation_time = '65' WHERE item_id = 'I109';
UPDATE ItemData SET item_name = 'Miso Soup', cuisine_type = 'Japanese', price = '29.22', calories = '301', item_type = 'Dessert', preparation_time = '11' WHERE item_id = 'I110';
UPDATE ItemData SET item_name = 'Tempura', cuisine_type = 'Japanese', price = '39.94', calories = '674', item_type = 'Beverage', preparation_time = '116' WHERE item_id = 'I111';
UPDATE ItemData SET item_name = 'Tiramisu', cuisine_type = 'Italian', price = '34.0', calories = '605', item_type = 'Beverage', preparation_time = '38' WHERE item_id = 'I112';
UPDATE ItemData SET item_name = 'Sweet and Sour Pork', cuisine_type = 'Chinese', price = '12.35', calories = '207', item_type = 'Starter', preparation_time = '35' WHERE item_id = 'I113';
UPDATE ItemData SET item_name = 'Miso Soup', cuisine_type = 'Japanese', price = '41.24', calories = '328', item_type = 'Starter', preparation_time = '43' WHERE item_id = 'I114';
UPDATE ItemData SET item_name = 'Spaghetti Carbonara', cuisine_type = 'Italian', price = '18.12', calories = '661', item_type = 'Starter', preparation_time = '10' WHERE item_id = 'I115';
UPDATE ItemData SET item_name = 'Burrito', cuisine_type = 'Mexican', price = '19.37', calories = '295', item_type = 'Starter', preparation_time = '5' WHERE item_id = 'I116';
UPDATE ItemData SET item_name = 'Sweet and Sour Pork', cuisine_type = 'Chinese', price = '15.03', calories = '256', item_type = 'Beverage', preparation_time = '41' WHERE item_id = 'I117';
UPDATE ItemData SET item_name = 'Kung Pao Chicken', cuisine_type = 'Chinese', price = '6.96', calories = '951', item_type = 'Dessert', preparation_time = '115' WHERE item_id = 'I118';
UPDATE ItemData SET item_name = 'Gulab Jamun', cuisine_type = 'Indian', price = '8.16', calories = '619', item_type = 'Main Course', preparation_time = '78' WHERE item_id = 'I119';
UPDATE ItemData SET item_name = 'Udon', cuisine_type = 'Japanese', price = '12.76', calories = '869', item_type = 'Beverage', preparation_time = '28' WHERE item_id = 'I120';
UPDATE ItemData SET item_name = 'Churros', cuisine_type = 'Mexican', price = '48.04', calories = '729', item_type = 'Starter', preparation_time = '6' WHERE item_id = 'I121';
UPDATE ItemData SET item_name = 'Spaghetti Carbonara', cuisine_type = 'Italian', price = '16.02', calories = '368', item_type = 'Starter', preparation_time = '47' WHERE item_id = 'I122';
UPDATE ItemData SET item_name = 'Enchiladas', cuisine_type = 'Mexican', price = '17.22', calories = '886', item_type = 'Starter', preparation_time = '30' WHERE item_id = 'I123';
UPDATE ItemData SET item_name = 'Rogan Josh', cuisine_type = 'Indian', price = '28.86', calories = '537', item_type = 'Dessert', preparation_time = '90' WHERE item_id = 'I124';
UPDATE ItemData SET item_name = 'Risotto', cuisine_type = 'Italian', price = '23.24', calories = '973', item_type = 'Beverage', preparation_time = '51' WHERE item_id = 'I125';
UPDATE ItemData SET item_name = 'Churros', cuisine_type = 'Mexican', price = '8.2', calories = '170', item_type = 'Beverage', preparation_time = '104' WHERE item_id = 'I126';
UPDATE ItemData SET item_name = 'Udon', cuisine_type = 'Japanese', price = '17.5', calories = '538', item_type = 'Beverage', preparation_time = '91' WHERE item_id = 'I127';
UPDATE ItemData SET item_name = 'Spaghetti Carbonara', cuisine_type = 'Italian', price = '8.23', calories = '624', item_type = 'Starter', preparation_time = '77' WHERE item_id = 'I128';
UPDATE ItemData SET item_name = 'Biryani', cuisine_type = 'Indian', price = '39.77', calories = '184', item_type = 'Beverage', preparation_time = '51' WHERE item_id = 'I129';
UPDATE ItemData SET item_name = 'Burrito', cuisine_type = 'Mexican', price = '7.09', calories = '398', item_type = 'Beverage', preparation_time = '67' WHERE item_id = 'I130';
UPDATE ItemData SET item_name = 'Burrito', cuisine_type = 'Mexican', price = '19.65', calories = '167', item_type = 'Beverage', preparation_time = '28' WHERE item_id = 'I131';
UPDATE ItemData SET item_name = 'Tiramisu', cuisine_type = 'Italian', price = '39.81', calories = '744', item_type = 'Main Course', preparation_time = '79' WHERE item_id = 'I132';
UPDATE ItemData SET item_name = 'Chiles Rellenos', cuisine_type = 'Mexican', price = '29.21', calories = '200', item_type = 'Beverage', preparation_time = '88' WHERE item_id = 'I133';
UPDATE ItemData SET item_name = 'Ramen', cuisine_type = 'Japanese', price = '32.88', calories = '560', item_type = 'Beverage', preparation_time = '44' WHERE item_id = 'I134';
UPDATE ItemData SET item_name = 'Fried Rice', cuisine_type = 'Chinese', price = '21.9', calories = '198', item_type = 'Starter', preparation_time = '120' WHERE item_id = 'I135';
UPDATE ItemData SET item_name = 'Miso Soup', cuisine_type = 'Japanese', price = '13.67', calories = '915', item_type = 'Starter', preparation_time = '81' WHERE item_id = 'I136';
UPDATE ItemData SET item_name = 'Udon', cuisine_type = 'Japanese', price = '37.52', calories = '953', item_type = 'Beverage', preparation_time = '49' WHERE item_id = 'I137';
UPDATE ItemData SET item_name = 'Burrito', cuisine_type = 'Mexican', price = '19.94', calories = '649', item_type = 'Main Course', preparation_time = '49' WHERE item_id = 'I138';
UPDATE ItemData SET item_name = 'Miso Soup', cuisine_type = 'Japanese', price = '34.22', calories = '269', item_type = 'Beverage', preparation_time = '68' WHERE item_id = 'I139';
UPDATE ItemData SET item_name = 'Gulab Jamun', cuisine_type = 'Indian', price = '44.8', calories = '241', item_type = 'Main Course', preparation_time = '107' WHERE item_id = 'I140';
UPDATE ItemData SET item_name = 'Tiramisu', cuisine_type = 'Italian', price = '22.46', calories = '228', item_type = 'Main Course', preparation_time = '114' WHERE item_id = 'I141';
UPDATE ItemData SET item_name = 'Udon', cuisine_type = 'Japanese', price = '14.66', calories = '674', item_type = 'Main Course', preparation_time = '96' WHERE item_id = 'I142';
UPDATE ItemData SET item_name = 'Rogan Josh', cuisine_type = 'Indian', price = '32.49', calories = '452', item_type = 'Dessert', preparation_time = '65' WHERE item_id = 'I143';
UPDATE ItemData SET item_name = 'Tiramisu', cuisine_type = 'Italian', price = '7.44', calories = '823', item_type = 'Starter', preparation_time = '35' WHERE item_id = 'I144';
UPDATE ItemData SET item_name = 'Pizza Margherita', cuisine_type = 'Italian', price = '44.3', calories = '735', item_type = 'Dessert', preparation_time = '23' WHERE item_id = 'I145';
UPDATE ItemData SET item_name = 'Burrito', cuisine_type = 'Mexican', price = '44.45', calories = '513', item_type = 'Beverage', preparation_time = '56' WHERE item_id = 'I146';
UPDATE ItemData SET item_name = 'Fried Rice', cuisine_type = 'Chinese', price = '22.47', calories = '422', item_type = 'Dessert', preparation_time = '91' WHERE item_id = 'I147';
UPDATE ItemData SET item_name = 'Enchiladas', cuisine_type = 'Mexican', price = '43.87', calories = '672', item_type = 'Starter', preparation_time = '33' WHERE item_id = 'I148';
UPDATE ItemData SET item_name = 'Mapo Tofu', cuisine_type = 'Chinese', price = '21.04', calories = '122', item_type = 'Dessert', preparation_time = '71' WHERE item_id = 'I149';
UPDATE ItemData SET item_name = 'Wonton Soup', cuisine_type = 'Chinese', price = '27.5', calories = '583', item_type = 'Dessert', preparation_time = '15' WHERE item_id = 'I150';
UPDATE ItemData SET item_name = 'Biryani', cuisine_type = 'Indian', price = '46.29', calories = '723', item_type = 'Dessert', preparation_time = '21' WHERE item_id = 'I151';
UPDATE ItemData SET item_name = 'Burrito', cuisine_type = 'Mexican', price = '35.93', calories = '431', item_type = 'Starter', preparation_time = '119' WHERE item_id = 'I152';
UPDATE ItemData SET item_name = 'Sweet and Sour Pork', cuisine_type = 'Chinese', price = '37.32', calories = '827', item_type = 'Main Course', preparation_time = '61' WHERE item_id = 'I153';
UPDATE ItemData SET item_name = 'Udon', cuisine_type = 'Japanese', price = '31.74', calories = '251', item_type = 'Beverage', preparation_time = '109' WHERE item_id = 'I154';
UPDATE ItemData SET item_name = 'Sweet and Sour Pork', cuisine_type = 'Chinese', price = '49.14', calories = '618', item_type = 'Dessert', preparation_time = '99' WHERE item_id = 'I155';
UPDATE ItemData SET item_name = 'Pizza Margherita', cuisine_type = 'Italian', price = '19.15', calories = '975', item_type = 'Dessert', preparation_time = '64' WHERE item_id = 'I156';
UPDATE ItemData SET item_name = 'Tacos', cuisine_type = 'Mexican', price = '19.92', calories = '319', item_type = 'Starter', preparation_time = '89' WHERE item_id = 'I157';
UPDATE ItemData SET item_name = 'Kung Pao Chicken', cuisine_type = 'Chinese', price = '26.5', calories = '573', item_type = 'Main Course', preparation_time = '59' WHERE item_id = 'I158';
UPDATE ItemData SET item_name = 'Butter Chicken', cuisine_type = 'Indian', price = '32.1', calories = '562', item_type = 'Beverage', preparation_time = '97' WHERE item_id = 'I159';
UPDATE ItemData SET item_name = 'Fried Rice', cuisine_type = 'Chinese', price = '39.01', calories = '425', item_type = 'Dessert', preparation_time = '95' WHERE item_id = 'I160';
UPDATE ItemData SET item_name = 'Pizza Margherita', cuisine_type = 'Italian', price = '21.4', calories = '220', item_type = 'Beverage', preparation_time = '105' WHERE item_id = 'I161';
UPDATE ItemData SET item_name = 'Wonton Soup', cuisine_type = 'Chinese', price = '31.79', calories = '991', item_type = 'Starter', preparation_time = '7' WHERE item_id = 'I162';
UPDATE ItemData SET item_name = 'Wonton Soup', cuisine_type = 'Chinese', price = '21.25', calories = '357', item_type = 'Starter', preparation_time = '5' WHERE item_id = 'I163';
UPDATE ItemData SET item_name = 'Burrito', cuisine_type = 'Mexican', price = '19.1', calories = '813', item_type = 'Main Course', preparation_time = '98' WHERE item_id = 'I164';
UPDATE ItemData SET item_name = 'Churros', cuisine_type = 'Mexican', price = '29.54', calories = '802', item_type = 'Starter', preparation_time = '36' WHERE item_id = 'I165';
UPDATE ItemData SET item_name = 'Chiles Rellenos', cuisine_type = 'Mexican', price = '46.69', calories = '512', item_type = 'Main Course', preparation_time = '54' WHERE item_id = 'I166';
UPDATE ItemData SET item_name = 'Lasagna', cuisine_type = 'Italian', price = '8.03', calories = '894', item_type = 'Main Course', preparation_time = '100' WHERE item_id = 'I167';
UPDATE ItemData SET item_name = 'Mapo Tofu', cuisine_type = 'Chinese', price = '45.41', calories = '422', item_type = 'Beverage', preparation_time = '102' WHERE item_id = 'I168';
UPDATE ItemData SET item_name = 'Kung Pao Chicken', cuisine_type = 'Chinese', price = '24.95', calories = '716', item_type = 'Dessert', preparation_time = '53' WHERE item_id = 'I169';
UPDATE ItemData SET item_name = 'Udon', cuisine_type = 'Japanese', price = '41.87', calories = '898', item_type = 'Beverage', preparation_time = '95' WHERE item_id = 'I170';
UPDATE ItemData SET item_name = 'Fried Rice', cuisine_type = 'Chinese', price = '17.36', calories = '631', item_type = 'Starter', preparation_time = '110' WHERE item_id = 'I171';
UPDATE ItemData SET item_name = 'Chiles Rellenos', cuisine_type = 'Mexican', price = '42.06', calories = '677', item_type = 'Main Course', preparation_time = '52' WHERE item_id = 'I172';
UPDATE ItemData SET item_name = 'Sweet and Sour Pork', cuisine_type = 'Chinese', price = '16.59', calories = '932', item_type = 'Main Course', preparation_time = '92' WHERE item_id = 'I173';
UPDATE ItemData SET item_name = 'Pizza Margherita', cuisine_type = 'Italian', price = '33.67', calories = '923', item_type = 'Dessert', preparation_time = '74' WHERE item_id = 'I174';
UPDATE ItemData SET item_name = 'Mapo Tofu', cuisine_type = 'Chinese', price = '24.01', calories = '357', item_type = 'Dessert', preparation_time = '65' WHERE item_id = 'I175';
UPDATE ItemData SET item_name = 'Mapo Tofu', cuisine_type = 'Chinese', price = '12.96', calories = '154', item_type = 'Starter', preparation_time = '17' WHERE item_id = 'I176';
UPDATE ItemData SET item_name = 'Tacos', cuisine_type = 'Mexican', price = '44.94', calories = '460', item_type = 'Dessert', preparation_time = '73' WHERE item_id = 'I177';
UPDATE ItemData SET item_name = 'Pizza Margherita', cuisine_type = 'Italian', price = '36.42', calories = '799', item_type = 'Main Course', preparation_time = '8' WHERE item_id = 'I178';
UPDATE ItemData SET item_name = 'Burrito', cuisine_type = 'Mexican', price = '8.9', calories = '177', item_type = 'Starter', preparation_time = '21' WHERE item_id = 'I179';
UPDATE ItemData SET item_name = 'Udon', cuisine_type = 'Japanese', price = '28.16', calories = '110', item_type = 'Beverage', preparation_time = '9' WHERE item_id = 'I180';
UPDATE ItemData SET item_name = 'Chole Bhature', cuisine_type = 'Indian', price = '12.14', calories = '454', item_type = 'Beverage', preparation_time = '35' WHERE item_id = 'I181';
UPDATE ItemData SET item_name = 'Tempura', cuisine_type = 'Japanese', price = '20.6', calories = '314', item_type = 'Beverage', preparation_time = '81' WHERE item_id = 'I182';
UPDATE ItemData SET item_name = 'Pizza Margherita', cuisine_type = 'Italian', price = '6.26', calories = '100', item_type = 'Beverage', preparation_time = '27' WHERE item_id = 'I183';
UPDATE ItemData SET item_name = 'Rogan Josh', cuisine_type = 'Indian', price = '37.69', calories = '700', item_type = 'Main Course', preparation_time = '93' WHERE item_id = 'I184';
UPDATE ItemData SET item_name = 'Rogan Josh', cuisine_type = 'Indian', price = '43.15', calories = '698', item_type = 'Beverage', preparation_time = '120' WHERE item_id = 'I185';
UPDATE ItemData SET item_name = 'Miso Soup', cuisine_type = 'Japanese', price = '17.43', calories = '560', item_type = 'Starter', preparation_time = '96' WHERE item_id = 'I186';
UPDATE ItemData SET item_name = 'Butter Chicken', cuisine_type = 'Indian', price = '37.81', calories = '671', item_type = 'Starter', preparation_time = '38' WHERE item_id = 'I187';
UPDATE ItemData SET item_name = 'Spaghetti Carbonara', cuisine_type = 'Italian', price = '30.91', calories = '487', item_type = 'Main Course', preparation_time = '117' WHERE item_id = 'I188';
UPDATE ItemData SET item_name = 'Sweet and Sour Pork', cuisine_type = 'Chinese', price = '11.16', calories = '907', item_type = 'Dessert', preparation_time = '89' WHERE item_id = 'I189';
UPDATE ItemData SET item_name = 'Ramen', cuisine_type = 'Japanese', price = '38.71', calories = '272', item_type = 'Beverage', preparation_time = '62' WHERE item_id = 'I190';
UPDATE ItemData SET item_name = 'Sweet and Sour Pork', cuisine_type = 'Chinese', price = '5.19', calories = '801', item_type = 'Dessert', preparation_time = '106' WHERE item_id = 'I191';
UPDATE ItemData SET item_name = 'Risotto', cuisine_type = 'Italian', price = '14.43', calories = '655', item_type = 'Starter', preparation_time = '107' WHERE item_id = 'I192';
UPDATE ItemData SET item_name = 'Enchiladas', cuisine_type = 'Mexican', price = '29.68', calories = '503', item_type = 'Dessert', preparation_time = '96' WHERE item_id = 'I193';
UPDATE ItemData SET item_name = 'Butter Chicken', cuisine_type = 'Indian', price = '30.12', calories = '690', item_type = 'Starter', preparation_time = '95' WHERE item_id = 'I194';
UPDATE ItemData SET item_name = 'Chiles Rellenos', cuisine_type = 'Mexican', price = '19.75', calories = '758', item_type = 'Beverage', preparation_time = '13' WHERE item_id = 'I195';
UPDATE ItemData SET item_name = 'Enchiladas', cuisine_type = 'Mexican', price = '38.02', calories = '241', item_type = 'Dessert', preparation_time = '98' WHERE item_id = 'I196';
UPDATE ItemData SET item_name = 'Sweet and Sour Pork', cuisine_type = 'Chinese', price = '5.19', calories = '263', item_type = 'Beverage', preparation_time = '51' WHERE item_id = 'I197';
UPDATE ItemData SET item_name = 'Ramen', cuisine_type = 'Japanese', price = '27.52', calories = '463', item_type = 'Beverage', preparation_time = '70' WHERE item_id = 'I198';
UPDATE ItemData SET item_name = 'Miso Soup', cuisine_type = 'Japanese', price = '49.84', calories = '392', item_type = 'Starter', preparation_time = '28' WHERE item_id = 'I199';
UPDATE CustomerData SET zip_code = '15955', joined_date = STR_TO_DATE('2018-11-06', '%Y-%m-%d') WHERE customer_id = 'C200';
UPDATE CustomerData SET zip_code = '15408', joined_date = STR_TO_DATE('2019-04-12', '%Y-%m-%d')  WHERE customer_id = 'C199';
UPDATE CustomerData SET zip_code = '13306', joined_date = STR_TO_DATE('2019-01-29', '%Y-%m-%d')  WHERE customer_id = 'C198';
UPDATE CustomerData SET zip_code = '15955', joined_date = STR_TO_DATE('2019-04-12', '%Y-%m-%d')  WHERE customer_id = 'C197';
UPDATE CustomerData SET zip_code = '15408', joined_date = STR_TO_DATE('2019-04-12', '%Y-%m-%d')  WHERE customer_id = 'C187';
UPDATE CustomerData SET zip_code = '67011', joined_date = STR_TO_DATE('2018-11-06', '%Y-%m-%d')  WHERE customer_id = 'C27';
UPDATE CustomerData SET zip_code = '59625', joined_date = STR_TO_DATE('2019-01-29', '%Y-%m-%d')  WHERE customer_id = 'C67';
UPDATE CustomerData SET zip_code = '28400', joined_date = STR_TO_DATE('2018-11-06', '%Y-%m-%d')  WHERE customer_id = 'C100';
UPDATE CustomerData SET zip_code = '59625', joined_date = STR_TO_DATE('2021-06-05', '%Y-%m-%d')  WHERE customer_id = 'C96';
UPDATE CustomerData SET zip_code = '13306', joined_date = STR_TO_DATE('2021-06-05', '%Y-%m-%d')  WHERE customer_id = 'C37';
UPDATE CustomerData SET zip_code = '67011', joined_date = STR_TO_DATE('2018-11-06', '%Y-%m-%d')  WHERE customer_id = 'C23';
UPDATE CustomerData SET zip_code = '15955', joined_date = STR_TO_DATE('2019-04-12', '%Y-%m-%d')  WHERE customer_id = 'C72';
UPDATE CustomerData SET zip_code = '28400', joined_date = STR_TO_DATE('2019-01-29', '%Y-%m-%d')  WHERE customer_id = 'C162';
UPDATE CustomerData SET zip_code = '59099', joined_date = STR_TO_DATE('2018-11-06', '%Y-%m-%d')  WHERE customer_id = 'C123';
UPDATE CustomerData SET zip_code = '15955', joined_date = STR_TO_DATE('2019-04-12', '%Y-%m-%d')  WHERE customer_id = 'C143';
UPDATE CustomerData SET zip_code = '59625', joined_date = STR_TO_DATE('2019-01-29', '%Y-%m-%d')  WHERE customer_id = 'C23';
UPDATE CustomerData SET zip_code = '28400', joined_date = STR_TO_DATE('2018-11-06', '%Y-%m-%d')  WHERE customer_id = 'C03';
UPDATE CustomerData SET zip_code = '59099', joined_date = STR_TO_DATE('2019-01-29', '%Y-%m-%d')  WHERE customer_id = 'C72';
DELETE FROM OrdersData WHERE order_id = '21';
DELETE FROM OrdersData WHERE order_id = '32';
DELETE FROM OrdersData WHERE order_id = '45';
DELETE FROM OrdersData WHERE order_id = '72';
DELETE FROM OrdersData WHERE order_id = '21';
DELETE FROM OrdersData WHERE order_id = '81';
DELETE FROM OrdersData WHERE order_id = '82';
DELETE FROM OrdersData WHERE order_id = '65';
DELETE FROM OrdersData WHERE order_id = '123';
DELETE FROM OrdersData WHERE order_id = '127';
DELETE FROM OrdersData WHERE order_id = '172';
DELETE FROM OrdersData WHERE order_id = '198';
DELETE FROM OrdersData WHERE order_id = '87';
DELETE FROM OrdersData WHERE order_id = '90';
DELETE FROM OrdersData WHERE order_id = '67';
DELETE FROM OrdersData WHERE order_id = '167';
DELETE FROM OrdersData WHERE order_id = '149';
DELETE FROM OrdersData WHERE order_id = '129';
DELETE FROM OrdersData WHERE order_id = '05';
INSERT INTO OrdersData (order_id, customer_id, restaurant_id, employee_id, order_date, order_time, delivery_charges, distance_from_restaurant, prepared_time, out_for_delivery_time, delivered_time, pick_up_time, estimated_delivery_time, completion_time, cancellation_time, refund_time, payment_type, flag, tip_amount) VALUES ('21', 'C113', 'R71', 'E26', STR_TO_DATE('2022-04-20', '%Y-%m-%d'), STR_TO_DATE('19:08:57', '%H:%i:%s'), '16.3', '18.98', STR_TO_DATE('19:09:57', '%H:%i:%s'), STR_TO_DATE('19:10:57', '%H:%i:%s'), STR_TO_DATE('19:12:57', '%H:%i:%s'), STR_TO_DATE('19:11:57', '%H:%i:%s'), '23', STR_TO_DATE('19:13:57', '%H:%i:%s'), STR_TO_DATE('', '%H:%i:%s'), STR_TO_DATE('', '%H:%i:%s'), 'CASH', 'delivered', '1.29');
INSERT INTO OrdersData (order_id, customer_id, restaurant_id, employee_id, order_date, order_time, delivery_charges, distance_from_restaurant, prepared_time, out_for_delivery_time, delivered_time, pick_up_time, estimated_delivery_time, completion_time, cancellation_time, refund_time, payment_type, flag, tip_amount) VALUES ('32', 'C90', 'R174', 'E41', STR_TO_DATE('2022-03-12', '%Y-%m-%d'), STR_TO_DATE('00:11:16', '%H:%i:%s'), '8.97', '4.03', STR_TO_DATE('13:51:48', '%H:%i:%s'), STR_TO_DATE('14:21:48', '%H:%i:%s'), STR_TO_DATE('14:42:29', '%H:%i:%s'), STR_TO_DATE('14:22:48', '%H:%i:%s'), '36', STR_TO_DATE('14:52:49', '%H:%i:%s'), STR_TO_DATE('', '%H:%i:%s'), STR_TO_DATE('', '%H:%i:%s'), 'MASTER DEBIT', 'suspicious', '1.29');
INSERT INTO OrdersData (order_id, customer_id, restaurant_id, employee_id, order_date, order_time, delivery_charges, distance_from_restaurant, prepared_time, out_for_delivery_time, delivered_time, pick_up_time, estimated_delivery_time, completion_time, cancellation_time, refund_time, payment_type, flag, tip_amount) VALUES ('45', 'C178', 'R107', 'E25', STR_TO_DATE('2022-02-08', '%Y-%m-%d'), STR_TO_DATE('10:20:24', '%H:%i:%s'), '18.21', '18.39', STR_TO_DATE('10:21:24', '%H:%i:%s'), STR_TO_DATE('10:22:24', '%H:%i:%s'), STR_TO_DATE('10:24:24', '%H:%i:%s'), STR_TO_DATE('10:23:24', '%H:%i:%s'), '32', STR_TO_DATE('10:25:24', '%H:%i:%s'), STR_TO_DATE('', '%H:%i:%s'), STR_TO_DATE('', '%H:%i:%s'), 'MASTER CREDIT', 'cancelled', '5.62');
INSERT INTO OrdersData (order_id, customer_id, restaurant_id, employee_id, order_date, order_time, delivery_charges, distance_from_restaurant, prepared_time, out_for_delivery_time, delivered_time, pick_up_time, estimated_delivery_time, completion_time, cancellation_time, refund_time, payment_type, flag, tip_amount) VALUES ('72', 'C121', 'R71', 'E19', STR_TO_DATE('2022-02-16', '%Y-%m-%d'), STR_TO_DATE('16:16:44', '%H:%i:%s'), '18.09', '17.02', STR_TO_DATE('16:17:44', '%H:%i:%s'), STR_TO_DATE('16:18:44', '%H:%i:%s'), STR_TO_DATE('', '%H:%i:%s'), STR_TO_DATE('16:19:44', '%H:%i:%s'), '23', STR_TO_DATE('10:20:04', '%H:%i:%s'), STR_TO_DATE('09:20:35', '%H:%i:%s'), STR_TO_DATE('10:09:29', '%H:%i:%s'), 'AMEX DEBIT', 'cancelled', '5.16');
UPDATE ItemData SET cuisine_type = 'Chinese' WHERE item_id in('I306', 'I311','I319');